### ISSUE TITLE
[3.0.0beta1] Crash on TaskProgress

### ISSUE THREAD

**Issue by piercifani** [bignerdranch/Deferred#137] opened 2016-10-27 16:10 UTC
I cannot recreate it on a smaller project. But I'm getting consistent crashes on latest commit of the Swift 3 branch. The backtrace looks like this: ![](https://i.imgur.com/ZVLfdw0.jpg)

The logger says:

```_TtC8DeferredP33_9528CFABF28443747CE301F7DAD432BB13ProxyProgress object 0x127c17fa0 overreleased while already deallocating; break on objc_overrelease_during_dealloc_error to debug```

Building for ARM64 in DEBUG. Please let me know if there is a way to help debug this, and as always: THANKS!

**Comment by jeremy-w** [comment] 2016-10-27 16:55
Please set a breakpoint on `objc_overrelease_during_dealloc_error` as instructed by the message, and provide the backtrace at that point. It's interesting that the same progress appears to be griping about that a bajillion times in your log - curious if it's once per `upon` block.

Possibly unrelated to this, but repeated use of a weak variable seems to be inviting the variable to poof out from under you in the middle of a block. (That's what `-Wreceiver-is-weak` diagnoses in Obj-C code.) So the block in that sample should probably be doing `guard let update = progress else { return }`. I'd make that fix to your local copy and see if that helps, as well.

**Comment by zwaldowski** [comment] 2016-10-28 02:49
See if #138 helps.

**Comment by piercifani** [comment] 2016-10-28 17:51
It looks like I can still make it crash, but it's different now. I managed to create a sample gist:

https://gist.github.com/piercifani/dea9934a143c691a1e422182fe9aaf99

Execute that in the Release mode and you'll see the crash.

**Comment by zwaldowski** [comment] 2016-10-28 18:00
Remember to remove your observers. I'm not able to reproduce the crash now when `ProgressObserver` looks like:

```swift
class ProgressObserver: NSObject {

    fileprivate let onUpdate: (Progress) -> Void
    fileprivate let progress: Progress

    private static var kvoContext = false

    public init(progress: Progress, onUpdate: @escaping (Progress) -> Void) {
        self.progress = progress
        self.onUpdate = onUpdate
        super.init()
        progress.addObserver(self, forKeyPath: #keyPath(Progress.fractionCompleted), options: .new, context: &ProgressObserver.kvoContext)
    }

    deinit {
        progress.removeObserver(self, forKeyPath: #keyPath(Progress.fractionCompleted), context: &ProgressObserver.kvoContext)
    }

    override public func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
        guard context == &ProgressObserver.kvoContext, object as AnyObject === progress  else {
            return super.observeValue(forKeyPath: keyPath, of: object, change: change, context: context)
        }

        DispatchQueue.main.async {
            self.onUpdate(self.progress)
        }
    }
}
```

Please reopen if you're able to reproduce. I'll work on getting #138 merged.

**Closed by zwaldowski** 2016-10-28 18:00 UTC
Labels: bug

**Comment by piercifani** [comment] 2016-10-28 18:03
True! Thanks for your time!
